//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean CallMenu
        {
            get
            {
                return SteamVR_Actions.default_CallMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Skeleton LeftSkeleton
        {
            get
            {
                return SteamVR_Actions.default_LeftSkeleton;
            }
        }
        
        public virtual SteamVR_Action_Skeleton RightSkeleton
        {
            get
            {
                return SteamVR_Actions.default_RightSkeleton;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftPose
        {
            get
            {
                return SteamVR_Actions.default_LeftPose;
            }
        }
        
        public virtual SteamVR_Action_Pose RightPose
        {
            get
            {
                return SteamVR_Actions.default_RightPose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptics
        {
            get
            {
                return SteamVR_Actions.default_Haptics;
            }
        }
    }
}
